### ISSUE TITLE
Scroll-Driven Animations Spec Update

### ISSUE THREAD

**Issue by bramus** [ivanalbizu/scroll-timeline-linked-animations#1]
Hi ivan!

Thank you for writing these. Unfortunately, since creating your content, the specification has undergone a major rewrite, rendering your content out of date.

Instead of asking you to fix your demos and rewrite your article - which could take a lot of time – could you update your demo/post to include some kind of warning to flag that it uses an outdated syntax?

For your convenience, I’ve prepared [a little script](https://codepen.io/bramus/pen/ZEqMOLz) that you can include in your demos. When invoked, it will show a dialog with a notice. As for your written content, I think a little warning at the top ([see here for an example](https://codepen.io/bramus/pen/ZEqMOLz)) could be sufficient.

Could you please take a look?

Thanks,
Bramus.

**Comment by ivanalbizu** [comment]
Thank you very much Bramus!

He already updated my website and the PEN with the demo https://codepen.io/ivan_albizu/pen/wvPMomr.

I've been reading the new scroll-driven version for a long time, I want to do another demo.

Thank you very much for all the documentation you are creating, very useful to learn!

**Comment by bramus** [comment]
Awesome, thank you!
